// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using projx.Data;

namespace projx.Migrations
{
    [DbContext(typeof(MovimentacaoDataContext))]
    [Migration("20200113015751_Conta Usuario")]
    partial class ContaUsuario
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("projx.Models.Agendamento", b =>
                {
                    b.Property<int>("IdAgendamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("DataFinal")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<bool>("FlgAtivo")
                        .HasColumnType("bit");

                    b.Property<int?>("MovimentacaoIdMovimentacao")
                        .HasColumnType("int");

                    b.Property<string>("Periodicidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<decimal>("Tempo")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdAgendamento");

                    b.HasIndex("MovimentacaoIdMovimentacao");

                    b.ToTable("Agendamento");
                });

            modelBuilder.Entity("projx.Models.CategoriaMovimentacao", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DscCategoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<bool>("FlgAtivo")
                        .HasColumnType("bit");

                    b.HasKey("IdCategoria");

                    b.ToTable("CategoriaMovimentacao");
                });

            modelBuilder.Entity("projx.Models.Conta", b =>
                {
                    b.Property<int>("IdConta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Ativa")
                        .HasColumnType("bit")
                        .HasMaxLength(1);

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("DscConta")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TipoConta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("IdConta");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Conta");
                });

            modelBuilder.Entity("projx.Models.Movimentacao", b =>
                {
                    b.Property<int>("IdMovimentacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CategoriaIdCategoria")
                        .HasColumnType("int");

                    b.Property<int?>("ContaIdConta")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataLancamento")
                        .HasColumnType("datetime2");

                    b.Property<string>("DscDetalhada")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DscMovimentacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Natureza")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<int?>("UsuarioIdUsuario")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("money");

                    b.HasKey("IdMovimentacao");

                    b.HasIndex("CategoriaIdCategoria");

                    b.HasIndex("ContaIdConta");

                    b.HasIndex("UsuarioIdUsuario");

                    b.ToTable("Movimentacao");
                });

            modelBuilder.Entity("projx.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Login")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pswd")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("projx.Models.Agendamento", b =>
                {
                    b.HasOne("projx.Models.Movimentacao", "Movimentacao")
                        .WithMany()
                        .HasForeignKey("MovimentacaoIdMovimentacao");
                });

            modelBuilder.Entity("projx.Models.Conta", b =>
                {
                    b.HasOne("projx.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");
                });

            modelBuilder.Entity("projx.Models.Movimentacao", b =>
                {
                    b.HasOne("projx.Models.CategoriaMovimentacao", "Categoria")
                        .WithMany("Movimentacoes")
                        .HasForeignKey("CategoriaIdCategoria");

                    b.HasOne("projx.Models.Conta", "Conta")
                        .WithMany("Movimentacoes")
                        .HasForeignKey("ContaIdConta");

                    b.HasOne("projx.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioIdUsuario");
                });
#pragma warning restore 612, 618
        }
    }
}
